const constants = {
  ADD_ERROR: "ADD_ERROR",
  REMOVE_ERROR: "REMOVE_ERROR",
  TOGGLE_FILTER: "TOGGLE_FILTER",
  SET_FILTERS: "SET_FILTERS",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  PRODUCT_COUNT: "PRODUCT_COUNT"
}

export default constants